### ISSUE TITLE
动态加载的HTML如何另存为完整的HTML文件？

### ISSUE THREAD

**Issue by xixia123** [AngelLiang/WechatExporter-html2excel#1]
你好，我也使用过这个工具，请问下如何将动态加载的HTML如何另存为完整的HTML文件？方便告知一下嘛，谢谢大佬

**Comment by AngelLiang** [comment]
一般来说，在网页点击鼠标右键，然后点击【另存为】就可以了。
或者在网页按下ctrl+s快捷键也可以。
